services:
  db:
    image: postgres:15
    container_name: my-postgres-dev
    restart: always
    environment:
      - POSTGRES_DB=whoami_db
      - POSTGRES_USER=whoami_user
      - POSTGRES_PASSWORD=whoami_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-dev
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app_network

  transfermarkt-api:
    build: ./transfermarkt-api
    container_name: transfermarkt-api-dev
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./transfermarkt-api:/app 
    networks:
      - app_network

  data-populator:
    build: ./data-populator
    container_name: data-populator-dev
    restart: no
    depends_on:
      - db
      - transfermarkt-api
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=whoami_db
      - DB_USER=whoami_user
      - DB_PASS=whoami_password
      - TRANSFERMARKT_API_URL=http://transfermarkt-api:8000
    volumes:
      - ./data-populator:/app  # Mount source code for live changes
    networks:
      - app_network

  backend:
    build:
      context: ./backend      
    container_name: spring-backend-dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/whoami_db
      - SPRING_DATASOURCE_USERNAME=whoami_user
      - SPRING_DATASOURCE_PASSWORD=whoami_password
    ports:
      - "8080:8080"
    networks:
      - app_network

volumes:
  pgdata_dev:

networks:
  app_network:
